#%RAML 1.0
---
title: Messaging Presentation
uses:
  traits: lib/traits/traits.raml
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
# API resource definitions
#===============================================================
/otp:
  displayName: One Time Password
  post:
    is: [traits.BadRequestError, traits.InternalServerError]
    body:
      application/json:
        type: !include schemas/body/otp.json
    responses:
      200:
        body:
          application/json:
            type: !include schemas/body/otp-response.json
  /verify:
    displayName: One Time Password Verify
    post:
      is: [traits.BadRequestError, traits.InternalServerError]
      body:
        application/json:
          type: !include schemas/body/otp-verify.json
      responses:
        200:
          body:
            application/json:
              type: !include schemas/body/otp-verify-response.json