#%RAML 1.0
---
#===============================================================
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
#===============================================================
title: Messaging Persistence
uses:
  traits: lib/traits/traits.raml
version: v1
baseUri: "/{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
types:
#===============================================================
# API resource definitions
#===============================================================
/transactions:
  displayName: OTP Transactions
  post:
    is: [traits.BadRequestError, traits.InternalServerError]
    body:
      application/json:
        type: !include schemas/body/post-otp-transaction.json
    responses:
      200:
        body:
          application/json:
            type: !include schemas/body/post-otp-transaction-response.json
  /{transactionId}:
    displayName: Transaction
    uriParameters:
      transactionId:
        displayName: Transaction Identifier
        type: string
    get:
      is: [traits.BadRequestError, traits.InternalServerError]
      responses:
        200:
          body:
            application/json: !include schemas/body/get-otp-transaction-response.json
  /verify:
    displayName: Verify Transaction
    post:
      is: [traits.BadRequestError, traits.InternalServerError]
      body:
        application/json:
          type: !include schemas/body/verify-otp-transaction.json
      responses:
        200:
          body:
            application/json:
              type: !include schemas/body/verify-otp-transaction-response.json